import { readFileSync, writeFileSync, readdirSync, unlinkSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";

const SRC_JS = "app.src.js";
const SOURCE_PARTS = [
  "src/classification-service.js",
  "src/data-service.js",
  "src/utils.js",
  "src/photo-service.js",
  "src/main-page.js",
  "src/more-page.js",
  "src/boot.js",
];
const HTML_FILES = ["index.html", "more.html"];

function hashOf(buf) {
  return createHash("sha1").update(buf).digest("hex").slice(0, 10);
}

function replaceScriptSrc(html, newJsName) {
  return html.replace(/app\.[a-zA-Z0-9_-]+\.js(\?[^"']*)?/g, newJsName);
}

function replaceCssSrc(html, newCssName) {
  return html.replace(/app(\.[a-f0-9]{10})?\.css(\?[^"']*)?/g, newCssName);
}

for (const f of SOURCE_PARTS) {
  if (!existsSync(f)) {
    console.error(`Missing source part: ${f}`);
    process.exit(1);
  }
}

const bundledSource = [
  "// Generated by build.mjs. Edit src/*.js instead.",
  ...SOURCE_PARTS.map((f) => readFileSync(f, "utf8").trimEnd()),
].join("\n\n") + "\n";
writeFileSync(SRC_JS, bundledSource);

if (!existsSync(SRC_JS)) {
  console.error(`Missing generated source JS: ${SRC_JS}`);
  process.exit(1);
}

const jsBuf = Buffer.from(bundledSource);
const jsHash = hashOf(jsBuf);
const outJs = `app.${jsHash}.js`;
writeFileSync(outJs, jsBuf);

const cssBuf = readFileSync("app.css");
const cssHash = hashOf(cssBuf);
const outCss = `app.${cssHash}.css`;
writeFileSync(outCss, cssBuf);

// Update HTML to point at the new filenames
for (const f of HTML_FILES) {
  let html = readFileSync(f, "utf8");
  html = replaceScriptSrc(html, outJs);
  html = replaceCssSrc(html, outCss);
  writeFileSync(f, html);
}

// Clean up old hashed JS files
const jsFiles = readdirSync(".").filter(n => /^app\.[a-f0-9]{10}\.js$/.test(n));
for (const f of jsFiles) { if (f !== outJs) unlinkSync(f); }

// Clean up old hashed CSS files
const cssFiles = readdirSync(".").filter(n => /^app\.[a-f0-9]{10}\.css$/.test(n));
for (const f of cssFiles) { if (f !== outCss) unlinkSync(f); }

console.log(`Built: ${outJs}  ${outCss}`);
