import { readFileSync, writeFileSync, readdirSync, unlinkSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";

const SRC_JS = "app.src.js";
const SOURCE_PARTS = [
  "src/classification-service.js",
  "src/data-service.js",
  "src/utils.js",
  "src/photo-service.js",
  "src/main-page.js",
  "src/more-page.js",
  "src/boot.js",
];
const HTML_FILES = ["index.html", "more.html"];

function hashOf(buf) {
  return createHash("sha1").update(buf).digest("hex").slice(0, 10);
}

function replaceScriptSrc(html, newJsName) {
  return html.replace(/app\.[a-zA-Z0-9_-]+\.js(\?[^"']*)?/g, newJsName);
}

function replaceCssSrc(html, newCssName) {
  return html.replace(/app(\.[a-f0-9]{10})?\.css(\?[^"']*)?/g, newCssName);
}

for (const f of SOURCE_PARTS) {
  if (!existsSync(f)) {
    console.error(`Missing source part: ${f}`);
    process.exit(1);
  }
}

const bundledSource = [
  "// Generated by build.mjs. Edit src/*.js instead.",
  ...SOURCE_PARTS.map((f) => readFileSync(f, "utf8").trimEnd()),
].join("\n\n") + "\n";
writeFileSync(SRC_JS, bundledSource);

if (!existsSync(SRC_JS)) {
  console.error(`Missing generated source JS: ${SRC_JS}`);
  process.exit(1);
}

const jsBuf = Buffer.from(bundledSource);
const jsHash = hashOf(jsBuf);
const outJs = `app.${jsHash}.js`;
writeFileSync(outJs, jsBuf);

const cssBuf = readFileSync("app.css");
const cssHash = hashOf(cssBuf);
const outCss = `app.${cssHash}.css`;
writeFileSync(outCss, cssBuf);

// Update HTML to point at the new filenames
for (const f of HTML_FILES) {
  let html = readFileSync(f, "utf8");
  html = replaceScriptSrc(html, outJs);
  html = replaceCssSrc(html, outCss);
  writeFileSync(f, html);
}

// Clean up old hashed JS files
const jsFiles = readdirSync(".").filter(n => /^app\.[a-f0-9]{10}\.js$/.test(n));
for (const f of jsFiles) { if (f !== outJs) unlinkSync(f); }

// Clean up old hashed CSS files
const cssFiles = readdirSync(".").filter(n => /^app\.[a-f0-9]{10}\.css$/.test(n));
for (const f of cssFiles) { if (f !== outCss) unlinkSync(f); }

// Generate sw.js with current asset names baked in (cache version = JS hash so it updates on every deploy)
writeFileSync("sw.js", `// Generated by build.mjs — do not edit directly.
const CACHE = "fr-${jsHash}";
const PRECACHE = [
  "./",
  "./index.html",
  "./more.html",
  "./manifest.webmanifest",
  "./icon-192.png",
  "./icon-512.png",
  "./${outJs}",
  "./${outCss}",
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", e => {
  if (e.request.method !== "GET") return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(e.request).then(hit => {
      if (hit) return hit;
      return fetch(e.request).then(res => {
        if (res && res.ok) {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(() => caches.match("./index.html"));
    })
  );
});
`);

console.log(`Built: ${outJs}  ${outCss}`);
